# Generated by Django 5.1.3 on 2024-12-18 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('description', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('number_in_stock', models.PositiveSmallIntegerField(default=0, verbose_name='number of items')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_name'],
            },
        ),
    ]
